CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS schools (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(30) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(25),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_state VARCHAR(100),
    address_country VARCHAR(100),
    address_zip_code VARCHAR(20),
    active BIT NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    CONSTRAINT uk_schools_code UNIQUE (code),
    INDEX idx_school_name (name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    profile_picture VARCHAR(500),
    school_id VARCHAR(36),
    status VARCHAR(30) NOT NULL,
    email_verified BIT NOT NULL DEFAULT b'0',
    email_verification_token VARCHAR(100),
    email_verification_token_expiry DATETIME(6),
    password_reset_token VARCHAR(100),
    password_reset_token_expiry DATETIME(6),
    last_login_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    INDEX idx_user_school (school_id),
    INDEX idx_user_status (status),
    INDEX idx_user_password_reset_token (password_reset_token),
    CONSTRAINT fk_users_school FOREIGN KEY (school_id) REFERENCES schools (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_roles (
    user_id VARCHAR(36) NOT NULL,
    role_id VARCHAR(36) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    INDEX idx_user_roles_user_id (user_id),
    INDEX idx_user_roles_role_id (role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id VARCHAR(36) NOT NULL,
    token VARCHAR(255) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    revoked BIT NOT NULL DEFAULT b'0',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_token UNIQUE (token),
    INDEX idx_refresh_token_user (user_id),
    INDEX idx_refresh_token_expiry (expires_at),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS school_branches (
    id VARCHAR(36) NOT NULL,
    school_id VARCHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(30) NOT NULL,
    principal_name VARCHAR(150),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_state VARCHAR(100),
    address_country VARCHAR(100),
    address_zip_code VARCHAR(20),
    active BIT NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    INDEX idx_branch_school_id (school_id),
    INDEX idx_branch_code (code),
    CONSTRAINT fk_branch_school FOREIGN KEY (school_id) REFERENCES schools (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS academic_years (
    id VARCHAR(36) NOT NULL,
    school_id VARCHAR(36) NOT NULL,
    name VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    current_year BIT NOT NULL DEFAULT b'0',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    INDEX idx_ay_school_id (school_id),
    INDEX idx_ay_name (name),
    CONSTRAINT fk_ay_school FOREIGN KEY (school_id) REFERENCES schools (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS parent_guardians (
    id VARCHAR(36) NOT NULL,
    school_id VARCHAR(36) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(25),
    relationship VARCHAR(50),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_state VARCHAR(100),
    address_country VARCHAR(100),
    address_zip_code VARCHAR(20),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    INDEX idx_parent_school (school_id),
    INDEX idx_parent_email (email),
    CONSTRAINT fk_parent_school FOREIGN KEY (school_id) REFERENCES schools (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS students (
    id VARCHAR(36) NOT NULL,
    school_id VARCHAR(36) NOT NULL,
    admission_number VARCHAR(40) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    date_of_birth DATE,
    admission_date DATE NOT NULL,
    current_grade VARCHAR(30),
    section VARCHAR(30),
    status VARCHAR(30) NOT NULL,
    parent_id VARCHAR(36),
    address_street VARCHAR(255),
    address_city VARCHAR(100),
    address_state VARCHAR(100),
    address_country VARCHAR(100),
    address_zip_code VARCHAR(20),
    documents_json TEXT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(36),
    updated_by VARCHAR(36),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    CONSTRAINT uk_students_admission_number UNIQUE (admission_number),
    INDEX idx_student_school (school_id),
    INDEX idx_student_status (status),
    INDEX idx_student_grade (current_grade),
    CONSTRAINT fk_student_school FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_student_parent FOREIGN KEY (parent_id) REFERENCES parent_guardians (id)
) ENGINE=InnoDB;
